// <auto-generated />
using System;
using LibraryWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryWebAPI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20221017192234_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LibraryWebAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Launch")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxRented")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalRented")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jk Rowling",
                            Launch = new DateTime(2000, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxRented = 2,
                            Name = "Harry Potter e o Cálice de fogo",
                            PublisherId = 1,
                            Quantity = 10,
                            TotalRented = 1
                        },
                        new
                        {
                            Id = 2,
                            Author = "Drauzio Varella",
                            Launch = new DateTime(1999, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxRented = 4,
                            Name = "Estação Carandiru",
                            PublisherId = 3,
                            Quantity = 68,
                            TotalRented = 2
                        },
                        new
                        {
                            Id = 3,
                            Author = "Antoine de Saint-Exupéry",
                            Launch = new DateTime(1943, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxRented = 3,
                            Name = "O pequeno príncipe",
                            PublisherId = 4,
                            Quantity = 10,
                            TotalRented = 1
                        },
                        new
                        {
                            Id = 4,
                            Author = " Robert Cecil Martin",
                            Launch = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxRented = 3,
                            Name = "Code Clean",
                            PublisherId = 4,
                            Quantity = 10,
                            TotalRented = 1
                        },
                        new
                        {
                            Id = 5,
                            Author = "Margareth Mitchell",
                            Launch = new DateTime(1999, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxRented = 3,
                            Name = "E o vento levou",
                            PublisherId = 4,
                            Quantity = 10,
                            TotalRented = 1
                        });
                });

            modelBuilder.Entity("LibraryWebAPI.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "São Paulo",
                            Name = "Saraiva"
                        },
                        new
                        {
                            Id = 2,
                            City = "Rio de Janeiro",
                            Name = "Intríseca"
                        },
                        new
                        {
                            Id = 3,
                            City = "Fortaleza",
                            Name = "Arqueiro"
                        },
                        new
                        {
                            Id = 4,
                            City = "Fortaleza",
                            Name = "Bem me quer"
                        });
                });

            modelBuilder.Entity("LibraryWebAPI.Models.Rent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DevolutionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Rents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            DevolutionDate = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ForecastDate = new DateTime(2022, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentDate = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            DevolutionDate = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ForecastDate = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentDate = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            DevolutionDate = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ForecastDate = new DateTime(2022, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            DevolutionDate = new DateTime(2022, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ForecastDate = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        });
                });

            modelBuilder.Entity("LibraryWebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua A",
                            City = "Fortaleza",
                            Email = "rosa@gmail.com",
                            Name = "Rosalice Nogueira"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rua B",
                            City = "Caucaia",
                            Email = "ana@gmail.com",
                            Name = "Ana Pontes"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rua C",
                            City = "Fortaleza",
                            Email = "andre@gmail.com",
                            Name = "André Vieira"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Rua Gorvenador Sampaio",
                            City = "São Paulo",
                            Email = "marcos@gmail.com",
                            Name = "Marcos Aurélio"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Rua D",
                            City = "Rio de Janeiro",
                            Email = "antonia@gmail.com",
                            Name = "Antonia Villela"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Rua Avelino Marçal",
                            City = "Aquiraz",
                            Email = "juarez@gmail.com",
                            Name = "Juarez Fernandez"
                        });
                });

            modelBuilder.Entity("LibraryWebAPI.Models.Book", b =>
                {
                    b.HasOne("LibraryWebAPI.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryWebAPI.Models.Rent", b =>
                {
                    b.HasOne("LibraryWebAPI.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryWebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
